# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeekSeven' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeekSeven
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'SwiftyJSON', '~> 4.0'



end
